### ISSUE TITLE
A spotify (playable) playlist is shown

### ISSUE THREAD

**Issue by rieschel** [OscarLBergstrom/aip#22]

**Comment by OscarLBergstrom** [comment]
https://support.spotify.com/us/artists/article/embedded-players/

**Example**

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/6WxdQOxSDcV6iCc8i1x7pc?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

**Comment by OscarLBergstrom** [comment]
https://developer.spotify.com/documentation/embeds
